# Generated by Django 2.1.7 on 2020-07-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('ecommerceProject', '0002_auto_20200716_1003'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
