# Generated by Django 2.1.7 on 2020-07-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceProject', '0002_auto_20200716_1003'),
        ('buyer', '0002_auto_20200721_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceProject.UserProfile')),
            ],
        ),
    ]
